.TH MATHO-SUM 1 "" "Mathomatic" "Mathomatic Utilities"

.SH NAME
matho-sum \- sum large integers

.SH SYNOPSIS
.B matho-sum
[integers]

.SH DESCRIPTION
This command-line utility is optionally part of the
.BR mathomatic (1)
package.
It uses Python to sum many large integers separated by spaces or newlines.
The size of the integers is only limited by the available memory of the computer.
The single integer result is output to standard output, followed by a newline.

The integers to sum may be specified on the command line or
read from standard input.

.SH AUTHOR 
George Gesslein II (gesslein@mathomatic.org)
at "http://www.mathomatic.org".

.SH "REPORTING BUGS"
If you find a bug, please report it to the author
or at "https://launchpad.net/mathomatic".

.SH "SEE ALSO"
.BR mathomatic (1),
.BR primorial (1),
.BR matho-mult (1)
